env: "dev"
http_server:
  address: "localhost:8080"
  timeout: 4s
  idle_timeout: 60s
storage:
  mongodb:
    dsn: "mongodb://root:example@localhost:27017/commentsdb?authSource=admin"
    db_name: "commentsdb"
